name: expense_trucker
description: "A simple expense tracker app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0  # Updated to latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Downgraded to compatible version

flutter:
  uses-material-design: true